CREATE TABLE IF NOT EXISTS cares (
    id BIGSERIAL PRIMARY KEY,
    plant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    last_care TIMESTAMP NOT NULL,
    next_care TIMESTAMP NOT NULL,
    name VARCHAR(255) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (plant_id) REFERENCES plants(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);